test pl 11

diff --git a/cicd/templates/01-cluster-tasks/image-digest-cluster-task.yaml b/cicd/templates/01-cluster-tasks/image-digest-cluster-task.yaml
--- a/cicd/templates/01-cluster-tasks/image-digest-cluster-task.yaml
+++ b/cicd/templates/01-cluster-tasks/image-digest-cluster-task.yaml
@@ -14,36 +14,48 @@ spec:
   description: >-
     These Task finds an image and returns the digest.
   params:
-    - description: Image Tag Name
-      name: IMAGE_TAG_NAME
+    - description: Image + Tag to find
+      name: IMAGE_TAG
       type: string
-    - description: Image Tag Namespace
-      name: IMAGE_TAG_NAMESPACE
+    - description: Namespace to find the image in
+      name: SEARCH_NAMESPACE
       type: string
+      default: ""
     - default: quay.io/atarazana/jq:0.0.2
-      description: the image used where the yq binary is
+      description: the image used where the jq binary is
       name: TASK_IMAGE
       type: string
   results:
-    - description: Digest of the image just built.
-      name: IMAGE_DIGEST
     - description: Digest of the image just built without "sha256:"
       name: IMAGE_DIGEST_CLEAN
+    - description: It shows if the process worked out fine or not 
+      name: SUCCESS
   steps:
     - image: $(params.TASK_IMAGE)
-      name: eval
+      name: find-image
       resources: {}
-      workingDir: $(workspaces.source.path)
       script: |
         #!/bin/sh
 
-        IMAGE_DIGEST = oc get imagetags $(params.IMAGE_TAG_NAME) -n $(params.IMAGE_TAG_NAMESPACE) | jq -r .image.metadata.name
-        echo "IMAGE_DIGEST: ${IMAGE_DIGEST}"
-        NEW_IMAGE_TAG = ("${IMAGE_DIGEST}" =~ /.*\:(.*)/)[0][1]
-        echo "NEW_IMAGE_TAG: ${NEW_IMAGE_TAG}"
+        IMAGE_TAG="$(params.IMAGE_TAG)"
+        SEARCH_NAMESPACE=$(params.SEARCH_NAMESPACE)
+        echo "IMAGE_TAG: ${IMAGE_TAG} SEARCH_NAMESPACE: ${SEARCH_NAMESPACE}"
 
-        echo -n ${IMAGE_DIGEST} > $(results.IMAGE_DIGEST)
-        echo -n ${NEW_IMAGE_TAG} > $(results.IMAGE_DIGEST_CLEAN)
-  workspaces:
-    - mountPath: /workspace/source
-      name: source
+        NAMESPACE_CLAUSE=$([[ ! -z "${SEARCH_NAMESPACE}" ]] && echo "-n ${SEARCH_NAMESPACE}" || echo "")
+        echo "NAMESPACE_CLAUSE: ${NAMESPACE_CLAUSE}"
+
+        IMAGE_DIGEST=$(oc get imagetags ${IMAGE_TAG} ${NAMESPACE_CLAUSE} | jq -r .image.metadata.name)
+        echo "IMAGE_TAG: ${IMAGE_TAG}"
+
+        PATTERN='.*\:(.*)'
+        if [[ ${IMAGE_TAG} =~ ${PATTERN} ]]; then 
+          IMAGE_DIGEST_CLEAN=${BASH_REMATCH[1]}
+        fi
+
+        if [ -z ${IMAGE_DIGEST_CLEAN} ]; then
+            echo "ERROR => IMAGE_DIGEST_CLEAN IS EMPTY"
+        else
+            echo "SUCCESS => IMAGE_DIGEST_CLEAN: ${IMAGE_DIGEST_CLEAN}"
+            # echo -n ${IMAGE_DIGEST_CLEAN} > $(results.IMAGE_DIGEST_CLEAN)
+        fi
+
